### ISSUE TITLE
Is data from ENAMDICT/JMnedict also incorporated in SudachiDict?

### ISSUE THREAD

**Issue by gopalkriagg** [WorksApplications/SudachiDict#4]
The data can be downloaded from: https://www.edrdg.org/enamdict/enamdict_doc.html
Thanks for great work!

**Comment by kazuma-t** [comment]
Thank you for your information.
ENAMDICT/JMnedict is distributed under Creative Commons Attribution-ShareAlike Licence (V3.0).
http://www.edrdg.org/edrdg/licence.html
This is not compatible with Apache License 2.0.  So we cannot merge this data.
