### ISSUE TITLE
How to compile the dictionary?

### ISSUE THREAD

**Issue by gopalkriagg** [WorksApplications/SudachiDict#7]
I am sorry for novice question, but I ran the following command
`sh package_python.sh` and it gave the following errors/warnings:
```
rm: target/python/20190718: No such file or directory
cp: target/system_small.dic: No such file or directory
```
Where can I find `system_small.dic`?

**Comment by kazuma-t** [comment]
Please run the Maven process first.
```
mvn clean package
```

**Comment by kazuma-t** [comment]
@izziiyt Can we use SudachiPy to build the dictionaries?

**Comment by gopalkriagg** [comment]
> Please run the Maven process first.
> 
> ```
> mvn clean package
> ```

Thanks! It worked!

**Comment by izziiyt** [comment]
@kazuma-t Yes. But I'm not so confident because I checked just a small input as unit test and manual test.   

However, just now I found I can check the correctness using data for (core/full/small) system.dic because you talked to me here.

Thanks.

**Comment by kazuma-t** [comment]
@izziiyt Thank you.
