### ISSUE TITLE
Comply with Section 4 of Apache License Version 2.0

### ISSUE THREAD

**Issue by overlast** [WorksApplications/SudachiDict#8]
## Motivation
Thank you for applying the assets of NEologd.

I found a small problem while doing a technical survey.

Unfortunately, as for NEologd only, I feel that the current implementation for python packages does not yet comply with the redistribution agreement described in section 4 of Apache License Version 2.0.

- http://www.apache.org/licenses/LICENSE-2.0#redistribution

    4. Redistribution. 
    You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
    a. You must give any other recipients of the Work or Derivative Works a copy of this License; and
    b. You must cause any modified files to carry prominent notices stating that You changed the files; and
    c. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
    d. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

## Goal

When time permits, please include the LEAGAL file not only this repository and sudachi-dictionary files but also following files.

- Python packages
    - SudachiDict_small-YYYYMMDD.tar.gz
    - SudachiDict_core-YYYYMMDD.tar.gz
    - SudachiDict_full-YYYYMMDD.tar.gz

**Comment by kazuma-t** [comment]
Thank you for pointing it out.
Resolved by #9.

**Comment by overlast** [comment]
Thank you !!
